[build]
publish = "www"
command = ""

[dev]
publish = "www"
command = ""

# This Netlify Build Plugin automatically registers this project in the Netlify
# Collect competition for Web Unleashed 2024.
[[plugins]]
package = "/plugins/register-submission/index.js"
